<h1>Урок 2. Матрицы и матричные операции</h1>

<h2>Часть 1</h2>

In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

<b>Решение</b>

а) Операция невозможна

б) $AB$ - матрица $2 \times 3$, $BA$ - операция невозможна

в) $AB$ - матрица $8 \times 8$, $BA$ - матрица $3 \times 3$

с) $AB$ и $BA$ - $4 \times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

<b>Решение</b>

$A + B = \begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


$A \cdot B = 
\begin{pmatrix}
1 \cdot 4 -2 \cdot 0 & -1 \cdot 1 -2 \cdot 5\\ 
3 \cdot 4 - 0 \cdot 0 & -1 \cdot 3 + 0 \cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}
$


In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A + B =\n {A+B}')
print(f'A * B =\n {np.dot(A, B)}')

A + B =
 [[ 5 -3]
 [ 3  5]]
A * B =
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

<b>Решение</b>

$$ 3A - 2B + 4C = 
3 \cdot \begin{pmatrix}
1 & 7 \\ 
3 & -6
\end{pmatrix}
- 2 \cdot \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix}
+4 \cdot \begin{pmatrix}
2 & -4 \\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 - 0 + 8 & 21 - 10 - 16\\ 
9 - 4 + 4 & -18 + 2 + 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}$$

In [3]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])
print(f'3*A - 2*B + 4*C = \n{3*A - 2*B + 4*C}')

3*A - 2*B + 4*C = 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

<b>Решение</b>

$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$


$ A \cdot A^{T} =
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = 
\begin{pmatrix}
16+1 & 20-2 & 8+3\\ 
20-2 & 25+4 & 10-6\\ 
8+3 & 10-6 & 4+9
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}
$





$A^{T} \cdot A = 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
\begin{pmatrix}
16 + 25 + 4 & 4 - 10 + 6 \\
4 - 10 + 6 & 1 + 4 + 9
\end {pmatrix}$ = $\begin{pmatrix}
45 & 0 \\
0 & 14
\end {pmatrix}$

In [4]:
A = np.array([[4,1], [5,-2], [2,3]])
print(f'A*A.T = \n{np.dot(A, A.T)}')
print(f'A.T*A = \n{np.dot(A.T, A)}')

A*A.T = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A.T*A = 
[[45  0]
 [ 0 14]]


<h2>Часть 2</h2>

__1.__ Вычислить определитель:

   a)
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б)
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

<b>Решение</b>

a)
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = \sin^2x + \cos^2x = 1;$

б)
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4(5\cdot9 - 1\cdot0) - 2(0\cdot9 - 0\cdot1) + 3(0\cdot0 - 0\cdot5) = 180$

в)
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 
1(5\cdot9 - 6\cdot8) -2(4\cdot9 - 6\cdot7) + 3(4\cdot8 - 5\cdot7) =
 45 - 48 - 72 + 84 + 96 - 105 = -3 - 72 + 84 - 9 =0$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

<b>Решение</b>


а) $det(A^{2}) = det(A \cdot A) = det(A)\cdot det(A) = 16$;

б) $det(A^{T}) = det(A) =4$;

в) $det(2A) = 2 \cdot det(A) = 8$.

__3.__  Доказать, что матрица

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   
вырожденная.

<b>Решение</b>

Вырожденная матрица - квадратная матрица, определитель которой равен 0. У данной матрицы определитель равен нулю, так как первые 2 строки равны линейно зависимы

In [5]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')
print(f'det(А):\n{round(np.linalg.det(A))}')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det(А):
0.0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

<b>Решение</b>


а) 3-я строка = 1-я строка + 2-я строка (убираем):

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\
\end{pmatrix}$

Вычтем из первой строки вторую

$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\
\end{pmatrix}$

rank = 2

In [6]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'ранг матрицы A равен {np.linalg.matrix_rank(A)}')

ранг матрицы A равен 2


б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

3-я строка = 1-я строка + 2-я строка (убираем):

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

rank = 3

In [7]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'ранг матрицы B равен {np.linalg.matrix_rank(B)}')

ранг матрицы B равен 3
