In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

<b>Решение</b>

$det(A-\lambda I)=\begin{vmatrix}
a_{11}-\lambda & a_{12}\\ 
a_{21} & a_{22}-\lambda
\end{vmatrix} = \lambda^{2}-(a_{11}+a_{22})\lambda+(a_{11}a_{22}-a_{12}a_{21}).$

<hr />

$det(A - \lambda I)$ = $0$
$\lambda^{2} - (-1 + 6)\lambda + (-6 + 12)$ = $\lambda^{2} - 5\lambda + 6$ = $0$

$D = b^{2} - 4ac$ = $(-5)^{2} - 4 * 1 * 6$ = $25 - 24$ = $1$

$\lambda_{1} = 2$

$\lambda_{2} = 3$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}$
$\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$

$\lambda = 2$

$\begin{cases}
-x_{1}-6x_{2} = 2x_{1}, \\
2x_{1}+6x_{2} = 2x_{2}.
\end{cases}$
$\Rightarrow
\begin{cases}
3x_{1} = -6x_{2}, \\
2x_{2} = -x_{1} .
\end{cases}$
$\Rightarrow
\begin{cases}
x_{1} = -2x_{2}, \\
2x_{2} = -x_{1} .
\end{cases}$
$\Rightarrow
\begin{cases}
x_{1} = -2, \\
x_{2} = 1 .
\end{cases}$

Собственный вектор v1 = (-2, 1)

$\lambda = 3$

$\begin{cases}
-x_{1}-6x_{2} = 3x_{1}, \\
2x_{1}+6x_{2} = 3x_{2}.
\end{cases}$
$\Rightarrow
\begin{cases}
4x_{1} = -6x_{2}, \\
2x_{1} = -3x_{2}.
\end{cases}$
$\Rightarrow
\begin{cases}
x_{1} = -\frac{3}{2}x_{2}, \\
x_{1} = -\frac{3}{2}x_{2}.
\end{cases}$
$\Rightarrow
\begin{cases}
x_{1} = \frac{3}{2}, \\
x_{2} = -1.
\end{cases}$

Собственный вектор v2 = ($\frac{3}{2}$, -1)

In [2]:
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

print(f'A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')
print(f'\nlambda = {w[1]}, x1 = {round(v[0,1] / v[1,1], 2)} * x2')
print(f'lambda = {w[0]}, x1 = {round(v[0,0] / v[1,0], 2)} * x2')

A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]

lambda = 3.0, x1 = -1.5 * x2
lambda = 2.0, x1 = -2.0 * x2


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

<b>Решение</b>

Собственный вектор оператора A — это такой ненулевой вектор, действие оператора на который сводится к умножению его на число: Ax=λx.

Пусть собственный вектор $x = \begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, тогда $Ax=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix} \begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix} = \lambda\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$


$ x_1 = - \lambda x_1; x_2 = - \lambda x_2 $

In [3]:
A = np.array([[-1, 0], [0, -1]])

print(f'A:\n{A}\n')

A:
[[-1  0]
 [ 0 -1]]



In [4]:
w, v = np.linalg.eig(A)

print(f'A:\n{A}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

A:
[[-1  0]
 [ 0 -1]]

Собственные значения:
[-1. -1.]

Собственные векторы:
[1. 0.], [0. 1.]



__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

<b>Решение</b>

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$

$\begin{cases}
1 + 1 = 1\cdot\lambda \\ 
-1 + 3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$

Ответ: вектор $𝑥=(1,1)$ является собственным вектором линейного оператора A, а его собственное значения составляет $\lambda=2$.

In [5]:
A = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]




__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

<b>Решение</b>


$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$

$
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
$ $\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}
$

Ответ: вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора A.

In [6]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
