<h2>Часть 1</h2>

In [1]:
import numpy as np
import scipy.linalg

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

<b>Решение</b>

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Умножим 1 строку на -2 и сложим со 2 строкой.

Вычтем из 3 строки 1 строку.

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

rank(A) = 3 = rank($\tilde{A}$) < n (4) => бесконечное количество решений

$x_{1} = -x_{2} + x_{3} + 2x_{4}$

$x_{2} = 2 + x_{3} + 5x_{4}$

$x_{3} = -2 + \frac{3}{2}x_{4}$

$x_{1} = -2 - 3с$

$x_{2} = \frac{13}{2}с$

$x_{3} = -2 + \frac{3}{2}с$

$x_{4} = с$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

<b>Решение</b>

$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\
2 & -5 & -3 \\
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4 \\
-17 \\
0
\end{matrix}
\end{pmatrix}$ = $\begin{pmatrix}
\left.\begin{matrix}
4 & 0 & 0 \\
2 & -5 & -3 \\
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4 \\
-17 \\
0
\end{matrix}
\end{pmatrix}$ = $\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
2 & -5 & -3 \\
4 & 0 & 0
\end{matrix}\right|
\begin{matrix}
0 \\
-17 \\
4
\end{matrix}
\end{pmatrix}$ 

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
-1 & -8 & 0 \\
4 & 0 & 0
\end{matrix}\right|
\begin{matrix}
0 \\
-17 \\
4
\end{matrix}
\end{pmatrix}$ = $\begin{pmatrix}
\left.\begin{matrix}
1 & -1 & -1\\
0 & -8 & -1\\
0 & 0 & 4
\end{matrix}\right|
\begin{matrix}
0 \\
-17 \\
4
\end{matrix}
\end{pmatrix}$ => rank(A) = rank($\tilde{A}$) = n = 3 => совместна, 1 решение.

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])


def print_results(A, A_ext, rank_A, rank_A_ext, n):
    print(f'A:\n{A}\n')
    print(f'A_ext:\n{A_ext}\n')

    print(f'rank(A) = {rank_A}\n')
    print(f'rank(A_ext) = {rank_A_ext}\n')
    print(f'Количество переменных: {n}\n')

    if rank_A == rank_A_ext == n:
        print(f'Система имеет единственное решение.')
    elif rank_A == rank_A_ext < n:
        print(f'Система имеет бесконечное кол-во решений.')
    elif rank_A < rank_A_ext:
        print(f'Система несовместна.')

print_results(A, A_ext, rank_A, rank_A_ext, n)

A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

A_ext:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

rank(A) = 3

rank(A_ext) = 3

Количество переменных: 3

Система имеет единственное решение.


   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\
1 & -2 & 3 \\
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
1 \\
-2 \\
5
\end{matrix}
\end{pmatrix}$ = $\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
2 & -4 & 6 \\
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
-2 \\
1 \\
5
\end{matrix}
\end{pmatrix}$ = $\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0 \\
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
-2 \\
5 \\
11
\end{matrix}
\end{pmatrix}$ => система несовместна, решений нет.

In [3]:
A = np.array([[3, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print_results(A, A_ext, rank_A, rank_A_ext, n)

A:
[[ 3 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

A_ext:
[[ 3 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

rank(A) = 2

rank(A_ext) = 3

Количество переменных: 3

Система несовместна.


   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$



$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\
3 & 1 & -8 \\
\end{matrix}
\right|
\begin{matrix}
4 \\
-2
\end{matrix}
\end{pmatrix}$

$\begin{vmatrix}
1 & 2 \\
3 & 1 \\
\end{vmatrix} = -5 \ne 0, $ $\begin{vmatrix}
1 & 5 \\
3 & -8 \\
\end{vmatrix} = -23 \ne 0, $ $\begin{vmatrix}
2 & 5 \\
1 & -8 \\
\end{vmatrix} = -21 \ne 0$ => $rank(A)=2, rank(B)=2$, но т.к. $n = 3$, то система неопределена, т.е. количество решений бесконечно.

In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print_results(A, A_ext, rank_A, rank_A_ext, n)

A:
[[ 1  2  5]
 [ 3  1 -8]]

A_ext:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

rank(A) = 2

rank(A_ext) = 2

Количество переменных: 3

Система имеет бесконечное кол-во решений.


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

<b>Решение</b>

$det(A) = 1\cdot5\cdot3\cdot2 = 30 \ne 0$ => матрица невырождена, количество неизвестных = количеству уравнений,

уравнения линейно независимые => решение есть и оно единственно.

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print_results(A, A_ext, rank_A, rank_A_ext, n)

A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

A_ext:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

rank(A) = 4

rank(A_ext) = 4

Количество переменных: 4

Система имеет единственное решение.


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$
$\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & 6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}$
$\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & 6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a-2b+8a
\end{matrix}
\end{pmatrix}$
$\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & 6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c+a-2b
\end{matrix}
\end{pmatrix}$

rank(A) = 2; rank(\tilde{A}) = 3; при c+a-2b $\neq$ 0

Получается, что система несовместна при c+a-2b $\neq$ 0

То есть: $a \neq 2b-c$, $b \neq \frac{a+c}{2}$, $c \neq 2b - a$

<h2>Часть 2</h2>

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

<b>Решение</b>

а) $detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4 
\end{vmatrix}= -4 - (-6)=2$

$detA_1=\begin{vmatrix}
1 & -2 \\ 
7 & -4 
\end{vmatrix}= -4 - (-14)=10$

$detA_2=\begin{vmatrix}
1 & 1 \\ 
3 & 7 
\end{vmatrix}= 7 - 3=4$

$x_1 = \frac{10}{2} = 5$

$x_2 = \frac{4}{2} = 2$

In [6]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

det_A = round(np.linalg.det(A))

print(f'A = \n{A}\n')
print(f'b = \n{b}\n')
print(f'det(A) = {det_A}\n')

A1 = np.column_stack([b, A[:, 1]])
det_A1 = round(np.linalg.det(A1))

print(f'A1 = \n{A1}\n')
print(f'det(A1) = {det_A1}\n')

A2 = np.column_stack([A[:, 0], b])
det_A2 = round(np.linalg.det(A2))

print(f'A2 = \n{A2}\n')
print(f'det(A2) =  {det_A2}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')

A = 
[[ 1 -2]
 [ 3 -4]]

b = 
[1 7]

det(A) = 2

A1 = 
[[ 1 -2]
 [ 7 -4]]

det(A1) = 10

A2 = 
[[1 1]
 [3 7]]

det(A2) =  4

x1 = 5.0
x2 = 2.0


б) $detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix}= 
2 \begin{vmatrix}
1 & -3 \\
4 & 1
\end{vmatrix} -
1 \begin{vmatrix}
-1 & 5\\ 
4 & 1
\end{vmatrix}+ 
2\begin{vmatrix}
-1 & 5\\ 
1 & -3 \\
\end{vmatrix}= 2(1+12)-(-1-20)+2(3-5) = 26 + 21 - 4 = 43$

$detA_1=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix} = 10(1+12)-(-2)(-1-20)+1(3-5) = 130 - 42 - 2 = 86$

$detA_2=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix}= 
2 \begin{vmatrix}
-2 & -3 \\
1 & 1
\end{vmatrix} -
1 \begin{vmatrix}
10 & 5\\ 
1 & 1
\end{vmatrix}+ 
2\begin{vmatrix}
10 & 5\\ 
-2 & -3 \\
\end{vmatrix}= 2(-2-(-3))-(10-5) +2(-30-(-10))= 2-5-40 = -43$

$detA_3=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix}= 
2 \begin{vmatrix}
1 & -2 \\
4 & 1
\end{vmatrix} -
1 \begin{vmatrix}
-1 & 10\\ 
4 & 1
\end{vmatrix}+ 
2\begin{vmatrix}
-1 & 10\\ 
1 & -2 \\
\end{vmatrix}=2(1-(-8)) - (-1-40) +2(2-10) = 18 + 41 - 16 = 43$

$x_1 = \frac{86}{43} = 2$

$x_2 = \frac{-43}{43} = -1$

$x_3 = \frac{43}{43} = 1$

In [7]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

det_A = round(np.linalg.det(A))

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

A1 = np.column_stack([b, A[:, 1:]])
det_A1 = round(np.linalg.det(A1))

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b, A[:, 2]])
det_A2 = round(np.linalg.det(A2))

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

A3 = np.column_stack([A[:, 0:2], b])
det_A3 = round(np.linalg.det(A3))

print(f'A3:\n{A3}\n')
print(f'det(A3): {det_A3}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')
print(f'x3 = {det_A3 / det_A}')

A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b:
[10 -2  1]

det(A): 43

A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

det(A1): 86

A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

det(A2): -43

A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

det(A3): 43

x1 = 2.0
x2 = -1.0
x3 = 1.0


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

<b>Решение</b>

$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$
$\Rightarrow 
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}
\Rightarrow 
\begin{cases}l_{21}=2 \\ l_{31}=3 \end{cases}
\Rightarrow 
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}
\Rightarrow 
(l_{32}=4)$

$L=\begin{pmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & 4 & 1 
\end{pmatrix}$

   б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [8]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.  0.  1.]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]



__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [9]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

K = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(K, b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]

