<h1>Урок 8</h1>

In [1]:
import numpy as np

<h2>Сингулярное разложение матриц</h2>

<b>1.</b>  Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

<b>Решение</b>

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

Получим разложение матрицы

In [3]:
U, s, W = np.linalg.svd(A)
U

array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
       [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
       [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
       [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
       [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

<b>Проверка</b>

Убедимся что матрица U диагональная

In [4]:
np.dot(U.T, U)

array([[ 1.00000000e+00,  3.19674802e-16, -3.99355622e-16,
         1.35663262e-17, -8.83091830e-18],
       [ 3.19674802e-16,  1.00000000e+00,  3.63628026e-16,
         7.29367646e-17,  3.15830273e-17],
       [-3.99355622e-16,  3.63628026e-16,  1.00000000e+00,
        -1.56755518e-16, -7.11991378e-17],
       [ 1.35663262e-17,  7.29367646e-17, -1.56755518e-16,
         1.00000000e+00, -2.63859021e-17],
       [-8.83091830e-18,  3.15830273e-17, -7.11991378e-17,
        -2.63859021e-17,  1.00000000e+00]])

In [5]:
s, W

(array([8.82486885, 6.14060608, 2.53271528]),
 array([[ 0.07116451,  0.71702467,  0.69340553],
        [-0.36737824,  0.66514082, -0.65009301],
        [-0.92734505, -0.20847855,  0.31075368]]))

Убедимся что матрица W диагональная

In [6]:
np.dot(W.T, W)

array([[ 1.00000000e+00,  1.82303571e-17,  8.52175949e-18],
       [ 1.82303571e-17,  1.00000000e+00, -1.70552412e-16],
       [ 8.52175949e-18, -1.70552412e-16,  1.00000000e+00]])

Получим матрицу V

In [7]:
V = W.T
V

array([[ 0.07116451, -0.36737824, -0.92734505],
       [ 0.71702467,  0.66514082, -0.20847855],
       [ 0.69340553, -0.65009301,  0.31075368]])

Найдем матрицу преобразования D

In [8]:
D = np.zeros_like(A, dtype=float)
D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
D[np.diag_indices(min(A.shape))] = s
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

Проведем проверку вычисления

In [10]:
np.dot(np.dot(U, D), V.T)

array([[ 1.00000000e+00,  2.00000000e+00,  1.31018987e-15],
       [ 1.93009612e-16, -2.66609409e-15,  5.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  6.00000000e+00,  5.00000000e+00],
       [-5.49534701e-17,  1.00000000e+00, -3.02821608e-17]])

In [11]:
np.dot(np.dot(U, D), V.T) - A

array([[-3.33066907e-16,  1.33226763e-15,  1.31018987e-15],
       [ 1.93009612e-16, -2.66609409e-15,  0.00000000e+00],
       [ 8.88178420e-16, -1.77635684e-15,  2.22044605e-15],
       [ 0.00000000e+00,  1.77635684e-15,  8.88178420e-16],
       [-5.49534701e-17,  4.44089210e-16, -3.02821608e-17]])

<b>2.</b> Для матрицы из предыдущего задания найти:

а) евклидову норму;

In [12]:
E_norm = D[0][0]
print(f'Trial(Euclidean norm) = {E_norm}\n')
print(f'Check(Euclidean norm) = {np.linalg.norm(A, ord=2)}\n')

Trial(Euclidean norm) = 8.824868854820444

Check(Euclidean norm) = 8.824868854820444



б) норму Фробениуса.

In [13]:
F_norm = np.sqrt(np.sum(np.power(D, 2)))
print(f'Trial(Frobenius norm) = {F_norm}\n')
print(f"Check(Frobenius norm) = {np.linalg.norm(A, ord='fro')}\n")

Trial(Frobenius norm) = 11.045361017187263

Check(Frobenius norm) = 11.045361017187261

